name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v5
      - name: Check Developer Mode Banned Symbols
        run: bash script/check_developer_mode_banned_symbols.sh
      - name: Build
        run: swift build
      - name: Test
        run: swift test
